In function 'test':
tests/cpychecker/refcounts/tp_iternext/partial-type-object/input.c:33:nn: warning: returning (PyObject*)NULL without setting an exception [enabled by default]
tests/cpychecker/refcounts/tp_iternext/partial-type-object/input.c:33:nn: note: returning at:     return NULL;
tests/cpychecker/refcounts/tp_iternext/partial-type-object/input.c:31:nn: note: graphical error report for function 'test' written out to 'tests/cpychecker/refcounts/tp_iternext/partial-type-object/input.c.test-refcount-errors.html'
